version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-foodradar}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -lc "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 foodradar.asgi:application"
    working_dir: /app/backend
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: bash -lc "celery -A foodradar worker -l info"
    working_dir: /app/backend
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: bash -lc "celery -A foodradar beat -l info"
    working_dir: /app/backend
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

volumes:
  db_data:
