# Generated by Django 4.2.14 on 2025-08-08 18:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан (корзина)'), ('pending_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('restaurant_confirmed', 'Ресторан подтвердил'), ('ready_for_pickup', 'Готов к выдаче'), ('accepted', 'Курьер принял'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='created', max_length=32, verbose_name='Статус')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe PaymentIntent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('client', 'Клиент'), ('courier', 'Курьер'), ('restaurant', 'Ресторан')], max_length=20, verbose_name='От кого')),
                ('stars', models.PositiveSmallIntegerField(default=5, verbose_name='Звезды')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
