# Generated by Django 4.2.14 on 2025-08-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='Метка времени')),
            ],
            options={
                'verbose_name': 'Локация курьера',
                'verbose_name_plural': 'Локации курьеров',
            },
        ),
    ]
