# Generated by Django 4.2.14 on 2025-08-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courierlocation',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AddIndex(
            model_name='courierlocation',
            index=models.Index(fields=['courier', '-ts'], name='idx_courier_ts_desc'),
        ),
    ]
